
palette = "snu1v3r" 

format = """\
[â•­â”€î‚²](bg:terminalback fg:terminalfront)\
[ ](fg:prev_bg bg:prev_fg)\
[$os]()\
$sudo\
[](fg:terminalback bg:terminalfront)\
[î‚´](fg:terminalfront bg:pathback)\
$directory\
${custom.gitclean}\
${custom.gitdirty}\
$git_status\
[î‚´](fg:prev_bg bg:terminalback)\
$fill\
[${custom.interface}](fg:terminalback bg:pathback)\
$hostname\
[î‚°](bg:terminalback fg:prev_bg)\
[â”€â•® ](bg:terminalback fg:terminalfront)\
$line_break\
[â•°â”€](bg:terminalback fg:terminalfront)\
$character\
"""

right_format = """\
[î‚¶](bg:terminalback fg:statusfront)\
$status\
$cmd_duration\
$time\
${custom.vpn}\
[î‚°](bg:terminalback fg:prev_bg)\
[â”€â•¯](bg:terminalback fg:terminalfront)\
"""


[hostname]
ssh_only = false
disabled = false
format = "[î‚¶](bg:prev_bg fg:hostback)[ ğŸ’» $hostname]($style)"
style = "fg:terminalback bg:hostback"

[os]
disabled = false
style = "fg:textfront bg:terminalfront"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
EndeavourOS = "ï†—"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
Pop = "ïŒª"

[directory]
format = "[ ](fg:pathfront bg:pathback)([$read_only]($read_only_style))[$path]($style)"
read_only_style = "fg:errorfront bg:prev_bg"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "â€¦/"
style = "fg:textfront bg:prev_bg"
#style = "fg:pathfront bg:pathback"

[git_branch]
#format = '[î‚´](bg:gitback fg:prev_bg)[ $symbol$branch(:$remote_branch) ]($style)'
format = '[î‚´](bg:gitback fg:prev_fg)[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "îœ‰ ï˜ "
#style = "fg:terminalback bg:gitback"
disabled = true
style = "fg:textfront bg:prev_fg"

[git_status]
conflicted = '=${count} '
untracked = '?${count} '
modified = '!${count} '
ahead = 'â‡¡${count} '
behind = 'â‡£${count} '
diverged = 'â‡•${count} '
stashed = 'îº†${count} '
deleted = 'ï€”${count} '
staged = '+${count} '
renamed = 'Â»${count} '
style = "fg:prev_fg bg:prev_bg"
format = '[${ahead_behind}${all_status}]($style)'
use_git_executable = false


[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = "ï˜ "

[cmd_duration]
min_time = 5000
format = "[î‚¶](fg:gitback bg:prev_bg )[ $duration ï‰’ ]($style)"
#format = "[î‚¶](bg:terminalback fg:terminalfront)[ $duration ï‰’ ]($style)[î‚¶](bg:gitback fg:terminalfront)"
style = "fg:textfront bg:gitback"

[character]
success_symbol = '[â¯](successfront)'
error_symbol = '[âœ—](errorfront)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
format = '[î‚¶](bg:prev_bg fg:terminalfront )[ $time ó±‘ ](fg:textfront bg:terminalfront)'

[fill]
symbol = 'â”€'
style = 'bg:terminalback fg:terminalfront'

[status]
symbol = '$int âœ˜ '
not_found_symbol = '$int ï„¨ '
success_symbol = 'âœ” '
success_style = 'fg:successfront bg:statusfront'
failure_style = 'fg:errorfront bg:statusfront'
format = '[$symbol]($style)'
signal_symbol ='ó±‹'
map_symbol = true
disabled = false

[sudo]
symbol = 'ó±‹'
style = 'fg:prev_fg bg:prev_bg'
format ='[ $symbol]($style)'
disabled = false

[custom.gitclean]
command = "git branch --show-current"
when = "git status | grep -q 'nothing to commit'"
format = "([î‚´](fg:prev_bg bg:successfront)[( îœ‰ ï˜ $output )]($style))"
style = 'fg:textfront bg:prev_bg'

[custom.gitdirty]
command = "git branch --show-current"
when = "! git status | grep -q 'nothing to commit'"
format = "([î‚´](fg:prev_bg bg:gitback)[ îœ‰ ï˜ $output ]($style))"
style = 'fg:textfront bg:prev_bg'

[custom.interface]
command = "ip route | grep -m1 default | awk '{print $9 \" ó°©  \" $5}'"
when = true
format = "([î‚¶](bg:prev_bg fg:pathback)[$output ]($style))"
style = 'fg:textfront bg:pathback'

[custom.vpn]
command = "ip route | head -n1 | awk '{print $3 \" ó± ¾ \" $5}'"
when = "ip route | head -n1 | grep -qE '(tun|tap)'"
format = "[î‚¶](bg:prev_bg fg:vpnback)[$output ]($style)"
style = 'fg:textfront bg:vpnback'

[palettes.snu1v3r]
terminalback = '#1A1B26' 
textfront = '#1A1B26' 
terminalfront = '#707691'
pathback = '#7299E5' 
#pathback = '#3465a4'
pathfront = '#D1D4D4'
gitback = '#CFA466'
statusfront = '#31344A'
successfront = '#98C86B'
errorfront = '#E84D44'
vpnback='#F1C0E4'
hostback='#F4B186'
